### ISSUE TITLE
O que é permitido para o exercício prático?

### ISSUE THREAD

**Issue by DiegoLopesLima** [db1global/mestre-dos-codigos#8]
Atualmente a descrição do exercício prático cita em alguns trechos a obrigatoriedade do **NÃO** uso de frameworks. Porém fiquei em duvida do que será considerado framework ou **NÃO PERMITIDO** em geral.

1. Posso utilizar pré-processadores como SASS ou Less por exemplo para o CSS?
2. Posso utilizar o Webpack e Babel para processar o javascript e gerar bundler?
3. O carrossel também deve ser feito sem o uso de ferramentas de terceiros em geral?

**Comment by juniormichieletto** [comment]
@adrianolobo pode responder está questão por favor?
Além disto é interessante adicionar estes detalhes, na página de frontend.

**Comment by adrianolobo** [comment]
Olá @DiegoLopesLima ,
A ideia da primeira primeira etapa do mestre dos código é se aproximar mais das linguagens em sua forma mais pura, para que assim crie uma maior base para os desafios maiores que as próximas etapas irão pedir. Portanto respondendo às suas perguntas:

1. Posso utilizar pré-processadores como SASS ou Less por exemplo para o CSS?
Não será permitido o uso de pré-processadores. Lembrando a estruturação, organização e padronização das nomenclaturas dos arquivos .css serão levadas em conta na hora da correção.

2. Posso utilizar o Webpack e Babel para processar o javascript e gerar bundler?
Não, já que no escudeiro ele não será avaliado e adicionaria uma complexidade maior, optamos por não liberarmos o uso a favor de termos um código mais perto de sua forma pura. Porém será permitido o uso do javascript ES6, já que o mesmo é compatível nativamente pelos maiores navegadores a um bom tempo.

3. O carrossel também deve ser feito sem o uso de ferramentas de terceiros em geral?
O carrossel deve ser desenvolvido usando HTML, CSS e JS, não será permitido o uso de ferramentas de terceiros. O intuito é validar o conhecimento de manipulação do D.O.M usando as APIs disponibilizadas nativamente.

Muito obrigado por ter postado a issue, irei enviar um PR detalhando mais esses pontos citados e alguns outros que imagino que possam surgir. 

Espero ter respondido suas dúvidas, caso tenha mais pode perguntar.

**Comment by larissapissurno** [comment]
@adrianolobo será permitido o uso de fontes como a fonte [awesome](https://fontawesome.com/)?

**Comment by adrianolobo** [comment]
Olá @larissapissurno ,

Sim, é permitido usar o font awesome, já que este é um recurso apenas estético, equivalente a utilizar os ícones como imagens ou importar fontes customizadas.

Irei adicionar isso na questão também, muito obrigado.
