### ISSUE TITLE
Para onde e como devo enviar as respostas para as perguntas apresentadas?

### ISSUE THREAD

**Issue by DiegoLopesLima** [db1global/mestre-dos-codigos#9]
1. Devo enviar para onde as resposta?
2. Em que formato (doc, pdf, etc...)?

**Comment by juniormichieletto** [comment]
Olá @DiegoLopesLima,
1. A submissão deve ser feita através do link do [formulário](https://forms.office.com/Pages/ResponsePage.aspx?id=GgBH6ig080COoYa9saO8hFLbN9UcS-dGnhQV9c5cN15UOUc5V0FFWlI3ODg4RE8xN05VTEtBSlAwWi4u) explicado no regulamento do MDC (https://mestredoscodigos.com.br/regulamento/).

2. No momento não existe um **padrão de formato** para envio, então fique à vontade para escolher a maneira mais fácil para você _(doc, pdf, github, etc)_ e disponibilizar conforme solicitado no [formulário de submissão](https://forms.office.com/Pages/ResponsePage.aspx?id=GgBH6ig080COoYa9saO8hFLbN9UcS-dGnhQV9c5cN15UOUc5V0FFWlI3ODg4RE8xN05VTEtBSlAwWi4u) 

* Recomendação: Se as respostas contiverem muito código, se torna mais fácil para a banca em o anexo dos arquivos em uma cloud ou disponibilizar via Github, bitbucket, etc.

**Comment by mkacunha** [comment]
@JuniorMiqueletti, acho importante conversar com cada coordenador de território definir as regras para envio das resoluções, pois no território de Java por exemplo foi exigido que todos as resoluções estejam em um repositório na GIT na nuvem, veja: https://db1global.github.io/mestre-dos-codigos/#/java?id=instru%c3%a7%c3%b5es

**Comment by juniormichieletto** [comment]
@mkacunha vamos abrir issues para isto então, pois implica em uma mudança até no form de submissão, ok?
@DiegoLopesLima está no território de frontend?

**Comment by mkacunha** [comment]
@JuniorMiqueletti  acho válido abrir a issue sim, e podemos abrir direto para cada coordenador de trilha, e eles abrirem um PR para nós depois.

**Comment by DiegoLopesLima** [comment]
@JuniorMiqueletti estou no território frontend sim.

**Comment by juniormichieletto** [comment]
Estamos fechando esta issue e qualquer coisa fique à vontade para abrir uma nova
obrigado @DiegoLopesLima
